
services:
  
  web:
    ports:
      - "80:80"
    image: gruimed/nginx-otel:0.1
    hostname: web
    volumes:
      - ./nginx/nginx-config.conf:/etc/nginx/conf.d/default.conf
    sysctls:
      net.ipv4.ip_local_port_range: "10240 65535"

    depends_on:
      - php-fpm
      - java-service

  java-service:
    build:
      context: java-service
      dockerfile: Dockerfile

    entrypoint: java  -jar /app/app.jar

  go-service:
    build:
      context: go-service
      dockerfile: Dockerfile

    sysctls:
      net.ipv4.ip_local_port_range: "10240 65535"

  php-composer:
    image: composer/composer:latest
    volumes:
      - ./www:/app
      - ./PHPFpm/composer.v1.json:/app/composer.json

    command: /bin/bash -c "composer update --ignore-platform-reqs"

  php-fpm:
    build:
      context: PHPFpm
      dockerfile: Dockerfile
    hostname: phpfpm
    sysctls:
      net.ipv4.ip_local_port_range: "10240 65535"

    volumes:
      - ./www:/usr/share/www
      - ./PHPFpm/composer.v1.json:/app/composer.json
      - ./PHPFpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./PHPFpm/docker.conf:/usr/local/etc/php-fpm.d/docker.conf

    depends_on:
      php-composer:
        condition: service_completed_successfully
  
  echo-service:
    build:
      context: echo-service
      dockerfile: Dockerfile
    hostname: echo-service

  pinba:
    image: gruimed/pinba:0.1
    hostname: pinba


# {{{ prometheus
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
#    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3030:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

# }}} prometheus
volumes:
  prom_data: